#Spring相关配置
spring:
#  profiles: 
  #thymeleaf配置
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: html
    prefix: classpath:/templates/
    suffix: .html
  #database配置
  datasource:
    url: jdbc:mysql://rm-bp102k9m31w3854p4o.mysql.rds.aliyuncs.com:3306/pqdt?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: datacenter
    password: mimabutigong
    filters: stat,wall
    maxActive: 100
    initialSize: 10
    minIdle: 1
    maxWait: 60000
  #Spring kafka 配置
  kafka:
    bootstrap-servers:
    - 192.168.0.197:9092
    - 192.168.0.198:9092
    - 192.168.0.199:9092
    producer:
      acks: all
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
server: 
  port: 8898
  
logging:
  level:
    com.gk: debug
    org.springframework: off
  
#MyBatis相关配置,无需手动写代码配置mybatis相关设置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gk.model

#PageHelper相关配置
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql 
 
#ElasticSearch基本配置  
es: 
  host: localhost
  port: 9300